// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PBL3_QuanLyDatXe.Data;

#nullable disable

namespace PBL3_QuanLyDatXe.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250511143124_updateDB_3")]
    partial class updateDB_3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PBL3_QuanLyDatXe.Models.Account", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("PBL3_QuanLyDatXe.Models.Bus", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("bienSo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("loaiXe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("soGhe")
                        .HasColumnType("int");

                    b.Property<string>("tenXe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Buses");
                });

            modelBuilder.Entity("PBL3_QuanLyDatXe.Models.Customer", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("CCCD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hoten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sodienthoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("PBL3_QuanLyDatXe.Models.Line", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("diemDen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("diemDi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tenTuyen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Lines");
                });

            modelBuilder.Entity("PBL3_QuanLyDatXe.Models.Ticket", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Customerid")
                        .HasColumnType("int");

                    b.Property<int>("Tripid")
                        .HasColumnType("int");

                    b.Property<DateTime>("ngayDat")
                        .HasColumnType("datetime2");

                    b.Property<int>("soGhe")
                        .HasColumnType("int");

                    b.Property<string>("trangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("Customerid");

                    b.HasIndex("Tripid");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("PBL3_QuanLyDatXe.Models.Trip", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("Busid")
                        .HasColumnType("int");

                    b.Property<int>("Routeid")
                        .HasColumnType("int");

                    b.Property<DateTime>("gioDi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ngayDi")
                        .HasColumnType("datetime2");

                    b.Property<int>("soGhe")
                        .HasColumnType("int");

                    b.Property<int>("sogheconTrong")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Busid");

                    b.HasIndex("Routeid");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("PBL3_QuanLyDatXe.Models.Customer", b =>
                {
                    b.HasOne("PBL3_QuanLyDatXe.Models.Account", "Account")
                        .WithOne("Customer")
                        .HasForeignKey("PBL3_QuanLyDatXe.Models.Customer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("PBL3_QuanLyDatXe.Models.Ticket", b =>
                {
                    b.HasOne("PBL3_QuanLyDatXe.Models.Customer", "Customer")
                        .WithMany("Tickets")
                        .HasForeignKey("Customerid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PBL3_QuanLyDatXe.Models.Trip", "Trip")
                        .WithMany("Tickets")
                        .HasForeignKey("Tripid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("PBL3_QuanLyDatXe.Models.Trip", b =>
                {
                    b.HasOne("PBL3_QuanLyDatXe.Models.Bus", null)
                        .WithMany("Trips")
                        .HasForeignKey("Busid");

                    b.HasOne("PBL3_QuanLyDatXe.Models.Line", "Route")
                        .WithMany("Trips")
                        .HasForeignKey("Routeid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");
                });

            modelBuilder.Entity("PBL3_QuanLyDatXe.Models.Account", b =>
                {
                    b.Navigation("Customer")
                        .IsRequired();
                });

            modelBuilder.Entity("PBL3_QuanLyDatXe.Models.Bus", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("PBL3_QuanLyDatXe.Models.Customer", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("PBL3_QuanLyDatXe.Models.Line", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("PBL3_QuanLyDatXe.Models.Trip", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
